---
- hosts: all
  become: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes    
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest    
    - name: install packages on localhost to allow use of SSH passwords
      apt: 
        name: sshpass
        state: latest
      